### ISSUE TITLE
What is bugcrowd your session token ? 

### ISSUE THREAD

**Issue by sabeesh03** [sw33tLie/bcscope#1]
What is bugcrowd your session token ?

**Comment by mzfr** [comment]
@sabeesh03 Basically log in to bugcrowd than open the developer tools in your browser and go to the cookies section there you should see the `_crowdcontrol_session` this token. That is the token that you have to use in this tool.

**Comment by sw33tLie** [comment]
@mzfr is right, thanks for replying :)
Closing this issue as resolved
